# Define workspaces with their representations
[workspace.1]
representation = "H[T[tmux browser-code]]"

[workspace.2]
representation = "H[discord V[browser-work yesugei]]"

# Define apps with their properties and commands
[app.tmux]
name = "kitty" # should be the desktop entry name w/o `.desktop`
cmd = "kitty -e tmux"
size = 70
post_cmd = ["wtype -M ctrl sr"]

[app.browser-code]
name = "firefox"
cmd = "firefox --new-window github.com"

[app.discord]
name = "discord"
cmd = "gtk-launch discord" # optional because name identical to gtk-launch
size = 30
delay = 3

[app.browser-work]
name = "firefox"
cmd = "firefox --new-window studio.youtube.com"
size = 70

[app.yesugei]
name = "kitty"
cmd = "kitty -d /mnt/yesugei/"

